// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Room
{
    public string RoomID { get; set; }

    public string RoomName { get; set; }

    public string SectionName { get; set; }

    public string CourseName { get; set; }
}
