// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Section
{
    public string SectionID { get; set; }

    public string SectionName { get; set; }

    public string Teacher { get; set; }
}