// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Student
{
    public string StudentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
}
