// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Teacher
{
    public string TeacherID { get; set; }

    public string TeacherName { get; set; }
}